### ISSUE TITLE
Migrations are broken

### ISSUE THREAD

**Issue by whit** [ella/ella#119]
It looks like problem is in commit  0cbcead140b7e145f584d20971db81ae4898be50

```
Running migrations for core:
 - Migrating forwards to 0009_auto__chg_field_publishable_last_updated.
 > core:0001_initial
 > photos:0001_initial
 > core:0002_initial_publishable
 > core:0002_remove_shit_add_columns
 > core:0002_remove_shit_data
 - Migration 'core:0002_remove_shit_data' is marked for no-dry-run.
 > core:0002_remove_shit_schema_cleanup
 > core:0003_add_field_publishable_published
 > core:0004_add_field_category_app_data_add_field_publishable_app_data
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/management/commands/migrate.py", line 107, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/__init__.py", line 219, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 235, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 310, in migrate_many
    result = self.migrate(migration, database)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 106, in run
    dry_run.run_migration(migration)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 191, in run_migration
    self._run_migration(migration)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 178, in _run_migration
    raise exceptions.FailedDryRun(migration, sys.exc_info())
south.exceptions.FailedDryRun:  ! Error found during dry run of '0004_add_field_category_app_data_add_field_publishable_app_data'! Aborting.
Traceback (most recent call last):
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 175, in _run_migration
    migration_function()
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/home/whit/Work/l/ella/ella/core/migrations/0004_add_field_category_app_data_add_field_publishable_app_data.py", line 12, in forwards
    orm['core.Category'].objects.filter(app_data='').update(app_data='{}')
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/orm.py", line 395, in __getattr__
    raise AttributeError("You are in a dry run, and cannot access the ORM.\nWrap ORM sections in 'if not db.dry_run:', or if the whole migration is only a data migration, set no_dry_run = True on the Migration class.")
AttributeError: You are in a dry run, and cannot access the ORM.
Wrap ORM sections in 'if not db.dry_run:', or if the whole migration is only a data migration, set no_dry_run = True on the Migration class.
```

**Comment by whit** [comment]
When i fix migration 0004, there are problems in article migrations:

```
Error in migration: articles:0002_add_field_article_content
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/management/commands/migrate.py", line 107, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/__init__.py", line 219, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 235, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 310, in migrate_many
    result = self.migrate(migration, database)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 107, in run
    return self.run_migration(migration)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 81, in run_migration
    migration_function()
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/home/whit/Work/l/ella/ella/articles/migrations/0002_add_field_article_content.py", line 16, in forwards
    article_ct = orm['contenttypes.ContentType'].objects.get(app_label='articles', model='article')
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/whit/Work/z/venvs/hope/lib/python2.7/site-packages/django/db/models/query.py", line 366, in get
    % self.model._meta.object_name)
django.contrib.contenttypes.models.DoesNotExist: ContentType matching query does not exist.
```

**Comment by honzakral** [comment]
don't use ContentType.objects.filter, instead use CT.objects.get_for_model(orm['articles.Article'])
