### ISSUE TITLE
Database error and PostgreSQL

### ISSUE THREAD

**Issue by alesbublik** [ella/ella#16]
In the branche "future/django-1.3" and with PostgreSQL backend appears Database error. Especially in the case of creating an article in the newman interface and with PostgreSQL (version 9.0). This bug doesn't appear with sqlite3 backend.

Traceback (most recent call last):
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/contrib/staticfiles/handlers.py", line 68, in **call**
    return self.application(environ, start_response)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 272, in **call**
    response = self.get_response(request)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/core/handlers/base.py", line 203, in handle_uncaught_exception
    return debug.technical_500_response(request, _exc_info)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, *_callback_kwargs)
  File "/home/budeb/work/ella/ella/newman/options.py", line 187, in wrapper
    return self.admin_site.admin_view(view)(_args, *_kwargs)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/utils/decorators.py", line 93, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/views/decorators/cache.py", line 79, in _wrapped_view_func
    response = view_func(request, _args, *_kwargs)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/contrib/admin/sites.py", line 197, in inner
    return view(request, _args, *_kwargs)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/db/transaction.py", line 217, in inner
    res = func(_args, *_kwargs)
  File "/home/budeb/work/ella/ella/newman/options.py", line 852, in add_json_view
    context = self.get_add_view_context(request, form_url)
  File "/home/budeb/work/ella/ella/newman/options.py", line 819, in get_add_view_context
    context = super(NewmanModelAdmin, self).get_add_view_context(request, form_url)
  File "/home/budeb/work/ella/ella/newman/xoptions.py", line 361, in get_add_view_context
    self.save_formset(request, form, formset, change=False)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/contrib/admin/options.py", line 677, in save_formset
    formset.save()
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/forms/models.py", line 482, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/forms/models.py", line 613, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/forms/models.py", line 717, in save_new
    obj.save()
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/db/models/base.py", line 460, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/db/models/base.py", line 553, in save_base
    result = manager._insert(values, return_id=update_pk, using=using)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/db/models/manager.py", line 195, in _insert
    return insert_query(self.model, values, **kwargs)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/db/models/query.py", line 1436, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 791, in execute_sql
    cursor = super(SQLInsertCompiler, self).execute_sql(None)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/db/backends/util.py", line 34, in execute
    return self.cursor.execute(sql, params)
  File "/home/budeb/.virtualenvs/sensa2/lib/python2.6/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
DatabaseError: can't adapt type 'UnicodeWrapper'

**Comment by honzakral** [comment]
This is a bug in django-markup that has just been fixed, upgrade that application and you should be fine.
