### ISSUE TITLE
Does not migrate on a fresh database

### ISSUE THREAD

**Issue by joshuajonah** [ella/ella#81]
I start with an empty database, install fresh version of Ella (it automatically downloads Django 1.3.1 as a dependency), do a `syncdb`, then try a `migrate`. 

This is the output:

``` python
Running migrations for core:
 - Migrating forwards to 0007_auto__chg_field_category_site__chg_field_related_related_ct__chg_field.
 > core:0001_initial
 > photos:0001_initial
 > core:0002_initial_publishable
 > core:0002_remove_shit
 > core:0003_add_field_publishable_published
 > core:0004_add_field_category_app_data_add_field_publishable_app_data
 > core:0005_auto__add_field_category_content__add_field_category_template
 > core:0006_add_publishable_announced
 > core:0007_auto__chg_field_category_site__chg_field_related_related_ct__chg_field
 - Loading initial data for core.
No fixtures found.
Running migrations for photos:
 - Migrating forwards to 0003_auto__chg_field_photo_created__chg_field_photo_image.
 > photos:0002_add_field_photo_app_data
 > photos:0003_auto__chg_field_photo_created__chg_field_photo_image
 - Loading initial data for photos.
No fixtures found.
Running migrations for articles:
 - Migrating forwards to 0005_initial.
 > articles:0001_initial
 > articles:0002_add_field_article_content
Traceback (most recent call last):
  File "project/manage.py", line 17, in <module>
    execute_manager(settings)
  File "/home/joshua/Development/backyardtimes/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/home/joshua/Development/backyardtimes/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/joshua/Development/backyardtimes/local/lib/python2.7/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/joshua/Development/backyardtimes/local/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/joshua/Development/backyardtimes/src/south/south/management/commands/migrate.py", line 107, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/joshua/Development/backyardtimes/src/south/south/migration/__init__.py", line 219, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/joshua/Development/backyardtimes/src/south/south/migration/migrators.py", line 235, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/joshua/Development/backyardtimes/src/south/south/migration/migrators.py", line 310, in migrate_many
    result = self.migrate(migration, database)
  File "/home/joshua/Development/backyardtimes/src/south/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration)
  File "/home/joshua/Development/backyardtimes/src/south/south/migration/migrators.py", line 106, in run
    dry_run.run_migration(migration)
  File "/home/joshua/Development/backyardtimes/src/south/south/migration/migrators.py", line 191, in run_migration
    self._run_migration(migration)
  File "/home/joshua/Development/backyardtimes/src/south/south/migration/migrators.py", line 178, in _run_migration
    raise exceptions.FailedDryRun(migration, sys.exc_info())
south.exceptions.FailedDryRun:  ! Error found during dry run of '0002_add_field_article_content'! Aborting.
Traceback (most recent call last):
  File "/home/joshua/Development/backyardtimes/src/south/south/migration/migrators.py", line 175, in _run_migration
    migration_function()
  File "/home/joshua/Development/backyardtimes/src/south/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/home/joshua/Development/backyardtimes/src/ella/ella/articles/migrations/0002_add_field_article_content.py", line 13, in forwards
    for ac in orm['articles.ArticleContents'].objects.all():
  File "/home/joshua/Development/backyardtimes/src/south/south/orm.py", line 395, in __getattr__
    raise AttributeError("You are in a dry run, and cannot access the ORM.\nWrap ORM sections in 'if not db.dry_run:', or if the whole migration is only a data migration, set no_dry_run = True on the Migration class.")
AttributeError: You are in a dry run, and cannot access the ORM.
Wrap ORM sections in 'if not db.dry_run:', or if the whole migration is only a data migration, set no_dry_run = True on the Migration class.
```

**Comment by honzakral** [comment]
@joshuajonah it seems that you are trying to run the migrations with dry_run, it's still a bug that ella doesn't handle that (fixing now) but note that migrations alone, without dry run actually work, try it for yourself in the test_ella project - add `south` to installed apps by adding a `settings/local.py` file containing:

  from test_ella.settings.base import INSTALLED_APPS
  INSTALLED_APPS += ('south', )

and then run `syncdb` and `migrate` works for me just fine on newest master.
