### ISSUE TITLE
Mass upload fails when uploading files with utf in file names

### ISSUE THREAD

**Issue by whit** [ella/ella#92]
```
ERROR:Exception handler:Traceback (most recent call last):
  File "/www/sensa/venv/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/www/sensa/venv/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 39, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "/www/sensa/venv/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 52, in wrapped_view
    return view_func(*args, **kwargs)
  File "/www/sensa/venv/lib/python2.6/site-packages/ella/photos/newman_admin.py", line 192, in upload_file_view
    context = self.get_mass_upload_context(request)
  File "/www/sensa/venv/lib/python2.6/site-packages/ella/photos/newman_admin.py", line 157, in get_mass_upload_context
    new_object.save()
  File "/www/sensa/venv/lib/python2.6/site-packages/ella/photos/models.py", line 136, in save
    super(Photo, self).save(force_insert, force_update)
  File "/www/sensa/venv/lib/python2.6/site-packages/django/db/models/base.py", line 460, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/www/sensa/venv/lib/python2.6/site-packages/django/db/models/base.py", line 543, in save_base
    for f in meta.local_fields if not isinstance(f, AutoField)]
  File "/www/sensa/venv/lib/python2.6/site-packages/django/db/models/fields/files.py", line 255, in pre_save
    file.save(file.name, file, save=False)
  File "/www/sensa/venv/lib/python2.6/site-packages/django/db/models/fields/files.py", line 92, in save
    self.name = self.storage.save(name, content)
  File "/www/sensa/venv/lib/python2.6/site-packages/django/core/files/storage.py", line 48, in save
    name = self.get_available_name(name)
  File "/www/sensa/venv/lib/python2.6/site-packages/django/core/files/storage.py", line 74, in get_available_name
    while self.exists(name):
  File "/www/sensa/venv/lib/python2.6/site-packages/django/core/files/storage.py", line 218, in exists
    return os.path.exists(self.path(name))
  File "/usr/lib/python2.6/genericpath.py", line 18, in exists
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0159' in position 55: ordinal not in range(128)
```

**Comment by Sixtease** [comment]
Jak to chceme řešit? Můžu zkusit udělat na straně JS filtr.

**Comment by xaralis** [comment]
No to by mělo být spíš ošetřené na straně pythonu.
